FROM alpine:latest
RUN apk update && apk add --no-cache nginx
RUN mkdir -p /var/www/localhost && \
    echo "<h1>Application Deployed via Terraform IaC!</h1>" > /var/www/localhost/index.html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
