# Utilise Alpine pour un conteneur léger
FROM alpine:latest

# Installer Nginx
RUN apk update && \
    apk add nginx && \
    rm -rf /var/cache/apk/*

# Créer la page HTML
RUN echo "<h1>Application Deployed via Terraform IaC!</h1>" \
    > /var/www/localhost/index.html

# Exposer le port
EXPOSE 80

# Lancer nginx en mode non-démon
CMD ["nginx", "-g", "daemon off;"]
